<?php

/**
 * @filename: 5bx
 * @project: 5BX API CLient Library
 * @description: Athorize test transactions against test gateway
 * @author: Steve George, steve@pagerange.com
 * @created_at: 6-Sep-2014
 * @updated_at: 21-Oct-2018
 */

/* DO NOT EDIT THIS FILE */

namespace Pagerange\Bx;

class _5bx {

  private $login_id; // your login ID
  private $api_key; // your API key
  private $amount;  // total sale amount
  private $card_type; // card type (visa, mastercard, ammex)
  private $card_number; // credit card number
  private $cvv; // cvv security number
  private $expiry_date; // expiry date in format mmyy
  private $reference_number; // your reference #  eg, invoice #.

  /**
   * @param String $login_id 5bx login id
   * @param String $api_key 5bx API key
   */
  public function __construct($login_id, $api_key) {

    $this->login_id = $login_id;
    $this->api_key = $api_key;

  }


  public function amount($amount) {
    $this->amount = $amount;
  }

  public function cvv($cvv) {
    $this->cvv = $cvv;
  }

  public function card_type($type) {
    $this->card_type = $type;
  }

  public function card_num($ccnum) {
    $this->card_number = $ccnum;
  }

  public function exp_date($exp_date) {
    $this->expiry_date = $exp_date;
  }

  public function ref_num($ref_num) {
    $this->reference_number = $ref_num;
  }


  public function authorize_and_capture(){

      $response = $this->__transmit();

      return json_decode($response);

  }

  /**
   * Send transaction data to Payment Gateway
   * and get JSON response in return.
   * @return JSON response
   */
  private function __transmit() {

    // Gateway URL
    $posturl = 'http://5bx.ca/bx/auth';

    //
    $postString = http_build_query($this, '', '&');

    $ch = curl_init();
    curl_setopt ($ch, CURLOPT_URL, $posturl);
    curl_setopt ($ch, CURLOPT_POST, 2);
    curl_setopt ($ch, CURLOPT_POSTFIELDS, $postString);
    curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
    $result = curl_exec ($ch);
    curl_close ($ch);

  return $result;

  }

}
