<?php

/**
 * @filename: 5bx
 * @project: 5BX API CLient Library
 * @description: Athorize test transactions against test gateway
 * @author: Steve George, steve@pagerange.com
 * @created_at: 6-Sep-2014
 * @updated_at: 21-Oct-2018
 */

/* DO NOT EDIT THIS FILE */

namespace Pagerange\Bx;





class _5bx {

  /**
   * array of parameters to send by post to 5bx gateway
   * @var array
   */
  private $params = [];


  /**
   * @param String $login_id 5bx login id
   * @param String $api_key 5bx API key
   */
  public function __construct($login_id, $api_key) {

    $this->params['login_id'] = $login_id;
    $this->params['api_key'] = $api_key;

  }

  /**
   * [amount description]
   * @param  [type] $amount Total amount of transaction
   * @return void
   */
  public function amount($amount) {
    $this->params['amount'] = $amount;
  }

  /**
   * CVV Secutity code
   * @param  Integer $cvv 
   * @return Void
   */
  public function cvv($cvv) {
    $this->params['cvv'] = $cvv;
  }

  /**
   * Thpe of credit card
   * @param  String Card type
   * @return Void
   */
  public function card_type($type) {
    $this->params['card_type'] = $type;
  }

  /**
   * Card number
   * @param  Integer $ccnum Credit card number
   * @return Void
   */
  public function card_num($ccnum) {
    $this->params['card_number'] = $ccnum;
  }

  /**
   * Expiry date
   * @param  String $exp_date Card expiry date
   * @return Void
   */
  public function exp_date($exp_date) {
    $this->params['expiry_date'] = $exp_date;
  }

  /**
   * Your reference number (order id)
   * @param  String $ref_num Your order ID 
   * @return Void
   */
  public function ref_num($ref_num) {
    $this->params['reference_number'] = $ref_num;
  }


  /**
   * Send data and return the transaction data
   * @return [type] [description]
   */
  public function authorize_and_capture(){

      $response = $this->__transmit();

      return json_decode($response);

  }

  /**
   * Send transaction data to Payment Gateway
   * and get JSON response in return.
   * @return JSON response
   */
  private function __transmit() {

    // Gateway URL
    $posturl = 'https://5bx.ca/bx/auth';

     //
    $post_data = json_encode($this->params);
    
    $headers=[];
    $headers[] = 'Content-Type: application/json';

    $ch = \curl_init();
    \curl_setopt ($ch, CURLOPT_URL, $posturl);
    \curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    \curl_setopt ($ch, CURLOPT_POST, 2);
    \curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
    \curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    \curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
    $result = \curl_exec ($ch);
    \curl_close ($ch);


  return $result;

  }

}
